ITEM.name = "Granada"
ITEM.description = "Uma pequena, verde granada MK3A2 que explode depois de alguns segundos depois de jogada."
ITEM.model = "models/weapons/w_grenade.mdl"
ITEM.class = "tfa_mmod_grenade"
ITEM.weaponCategory = "grenade"
ITEM.classes = {CLASS_EOW}
ITEM.flag = "V"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.1